"""flypaper - novelty ranking for web fuzzing output.

Reads ffuf results and ranks them by how structurally unusual they are, scored by the
fruit fly olfactory circuit: a sparse locality-sensitive hash (FlyHash) over a Bloom
filter that grades novelty by similarity and by time since last encounter.

It ranks; it does not detect. A novel response is a statistical outlier, not a
vulnerability. See README.md.
"""

from __future__ import annotations

import subprocess
from datetime import UTC, datetime
from pathlib import Path

__version__ = "0.1.0"

REPO_ROOT = Path(__file__).resolve().parent.parent

__all__ = [
    "REPO_ROOT",
    "__version__",
    "git_commit",
    "git_dirty",
    "provenance",
    "provenance_footer",
]


def git_commit(short: bool = False) -> str:
    """Return the current git commit hash, or 'unknown' outside a git checkout."""
    args = ["git", "-C", str(REPO_ROOT), "rev-parse"]
    if short:
        args.append("--short")
    args.append("HEAD")
    try:
        out = subprocess.run(args, capture_output=True, text=True, timeout=10, check=True)
    except (subprocess.SubprocessError, OSError):
        return "unknown"
    return out.stdout.strip() or "unknown"


def git_dirty() -> bool:
    """True if the code that produces a result is uncommitted.

    Generated output under `reports/` is excluded: a report is not made unreproducible by
    the fact that it, or a sibling report, has just been rewritten.
    """
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "status", "--porcelain", "--", ".", ":!reports"],
            capture_output=True,
            text=True,
            timeout=10,
            check=True,
        )
    except (subprocess.SubprocessError, OSError):
        return False
    return bool(out.stdout.strip())


def provenance(seed: int | None = None) -> dict[str, object]:
    """Provenance stamp for every generated report. Seed and commit, or it did not happen."""
    return {
        "flypaper_version": __version__,
        "git_commit": git_commit(),
        "git_dirty": git_dirty(),
        "generated_utc": datetime.now(UTC).isoformat(timespec="seconds"),
        "seed": seed,
    }


def provenance_footer(seed: int | None = None) -> str:
    """Markdown footer embedding the provenance stamp, appended to generated reports."""
    p = provenance(seed)
    dirty = " **(dirty working tree - not reproducible)**" if p["git_dirty"] else ""
    seed_str = f" | seed `{p['seed']}`" if p["seed"] is not None else ""
    return (
        f"\n---\n\n*Generated by flypaper {p['flypaper_version']} at commit "
        f"`{p['git_commit']}`{dirty}{seed_str} on {p['generated_utc']}.*\n"
    )
