"""Turn a bug bounty program's published scope into a flypaper scope file.

An operator who hand-copies a scope table into a text file will eventually copy a row they
should not have, and stage two will believe them. This does the copying, and its defining
property is that **it never authorises more than the program does**:

  * Assets the program marks not eligible for submission are dropped. In a survey of 164
    published scope tables, 526 of 1,930 assets - more than a quarter - were marked
    ineligible while sitting in the same table as the eligible ones.
  * Asset types that are not a web host are dropped: app store IDs, source code, hardware,
    executables. They are in scope for the *program*, not for a URL fuzzer.
  * An asset scoped to a path - `example.com/admin/*` - is **skipped, not truncated to its
    host**. Dropping the path would turn "this one path" into "this whole host", which is
    the single most dangerous thing a converter like this could do quietly.
  * CIDR ranges and anything that is not a host pattern are skipped and listed.

Everything dropped is reported, because a silent drop is how an operator ends up believing
an asset was covered when it was not.

    fly scope --from program-scope.csv --out scope.txt

The CSV is HackerOne's structured scope export: `identifier`, `asset_type`,
`eligible_for_submission`. Other columns are ignored.
"""

from __future__ import annotations

import csv
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from flypaper.stage2.scope import ScopeSyntaxError, check_pattern

__all__ = ["ConversionReport", "WEB_ASSET_TYPES", "convert_program_scope"]

#: Asset types that name something a URL fuzzer can address. Everything else is in scope
#: for the program and out of scope for this tool.
WEB_ASSET_TYPES = frozenset({"URL", "WILDCARD", "OTHER", "API", "IP_ADDRESS"})

_TRUTHY = frozenset({"true", "yes", "1"})


@dataclass
class ConversionReport:
    patterns: list[str] = field(default_factory=list)
    skipped: list[tuple[str, str, str]] = field(default_factory=list)  # identifier, type, why
    counts: Counter = field(default_factory=Counter)

    def summary(self) -> str:
        c = self.counts
        return (
            f"{len(self.patterns)} host patterns from {c['rows']} assets "
            f"({c['ineligible']} ineligible, {c['non_web']} not a web host, "
            f"{c['unusable']} not expressible as a host pattern)"
        )

    @property
    def uncovered_apexes(self) -> list[str]:
        """Apex domains that a `*.` wildcard here does not cover.

        `*.example.com` matches subdomains and not `example.com` itself - the conservative
        reading, because under-authorising is the safe direction. Programs differ on whether
        their wildcard includes the apex, so the gap is written into the file as a comment
        rather than either silently included or silently dropped.
        """
        have = set(self.patterns)
        apexes = []
        for pattern in self.patterns:
            if pattern.startswith("*."):
                apex = pattern[2:]
                if apex not in have and apex not in apexes:
                    apexes.append(apex)
        return apexes

    def write(self, path: str | Path, source: str = "") -> None:
        lines = [
            "# flypaper scope file.",
            f"# Generated by `fly scope` from {source or 'a program scope export'}.",
            "# Only assets the program marks eligible for submission are here, and nothing",
            "# path-scoped has been widened to its host. Check it against the program's own",
            "# page before you point anything at it: this file is a convenience, not an",
            "# authorisation.",
            "",
        ]
        lines += self.patterns

        apexes = self.uncovered_apexes
        if apexes:
            lines += [
                "",
                "# `*.example.com` covers subdomains, not the apex. Programs differ on whether",
                "# their wildcard includes it, so these are listed rather than assumed. Uncomment",
                "# the ones the program actually covers.",
            ]
            lines += [f"# {apex}" for apex in apexes]
        Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _eligible(row: dict) -> bool:
    value = (row.get("eligible_for_submission") or "").strip().lower()
    # Blank is not a yes. A scope table that does not say is not a table that authorises.
    return value in _TRUTHY


def convert_program_scope(path: str | Path) -> ConversionReport:
    """Read a program scope export and return the patterns it authorises, plus what was not."""
    report = ConversionReport()
    with Path(path).open(newline="", encoding="utf-8", errors="replace") as handle:
        for row in csv.DictReader(handle):
            identifier = (row.get("identifier") or "").strip()
            if not identifier:
                continue
            asset_type = (row.get("asset_type") or "").strip().upper()
            report.counts["rows"] += 1

            if not _eligible(row):
                report.counts["ineligible"] += 1
                report.skipped.append((identifier, asset_type, "not eligible for submission"))
                continue
            if asset_type not in WEB_ASSET_TYPES:
                report.counts["non_web"] += 1
                report.skipped.append((identifier, asset_type, f"{asset_type} is not a web host"))
                continue

            try:
                report.patterns.append(check_pattern(identifier))
            except ScopeSyntaxError as exc:
                report.counts["unusable"] += 1
                report.skipped.append((identifier, asset_type, str(exc)))

    # Order-preserving deduplication: the same host often appears under several types.
    report.patterns = list(dict.fromkeys(report.patterns))
    report.counts["patterns"] = len(report.patterns)
    return report
